name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: asahiocean
          base: main
          head: main
          merge_method: merge
          auto_approve: true
